name: Build, Test
on: push

jobs:
  docker-build:
    environment: test
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CENTOS_FTP_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_CENTOS_FTP_IMAGE_REPOSITORY }}
      CENTOS_FTP_IMAGE_REPOSITORY_TAG: latest
      BRANCH_NAME: ${{ github.ref }}

    name: Build and push Centos FTP Base image
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout project'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build FTP Client base image
        uses: docker/build-push-action@v2
        with:
          context: ./tests/ftp-client/
          file: ./tests/ftp-client/Dockerfile
          push: true
          tags: ${{ env.CENTOS_FTP_IMAGE_REPOSITORY }}:${{ env.CENTOS_FTP_IMAGE_REPOSITORY_TAG }}
  tests:
    environment: test
    env:
      CENTOS_FTP_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_CENTOS_FTP_IMAGE_REPOSITORY }}
      CENTOS_FTP_IMAGE_REPOSITORY_TAG: latest
    needs: [docker-build]
    name: Launch tests
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout project'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      -
        name: 'Installing npm'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      -
        name: 'Installing packages'
        working-directory: tests
        run: npm i
      -
        name: 'Set env'
        run: |
          export CENTOS_FTP_IMAGE_REPOSITORY=${{ env.CENTOS_FTP_IMAGE_REPOSITORY }}
          export CENTOS_FTP_IMAGE_REPOSITORY_TAG=${{ env.CENTOS_FTP_IMAGE_REPOSITORY_TAG }}
      -
        name: 'Launching tests'
        working-directory: tests
        run: npm run test
        