name: Publish
on:
  workflow_dispatch:
      inputs:
        tagVersion:
          description: 'Tag'
          required: true
          default: 'latest'

jobs:
  publish:
    environment: test
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      VSFTPD_IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_VSFTPD_IMAGE_REPOSITORY }}
      VSFTPD_IMAGE_TAG: ${{ github.event.inputs.tagVersion }}
      BRANCH_NAME: ${{ github.ref }}
    name: Build and push VSFTPD image
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout project'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and Push VSFTPD image latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.VSFTPD_IMAGE_REPOSITORY }}:latest
      -
        name: Build and Push VSFTPD image with specified version
        uses: docker/build-push-action@v2
        if: ${{ env.VSFTPD_IMAGE_TAG != 'latest' }}
        with:
          context: .
          push: true
          tags: ${{ env.VSFTPD_IMAGE_REPOSITORY }}:${{ env.VSFTPD_IMAGE_TAG }}
          